bot:
  url: https://api.telegram.org/bot
  name: FirstTestingBot
  token: 5412400820:AAHF5WCrHyoIi6QaB4ZgjjHWL5-VKNGqp60 # test


#kassa:
#  url: https://api.yookassa.ru/v3/payments
#  token: live_AYzNMtFUn6glv9Au67HK8GTXQMVqyercA26X78gazz8
#  shopID: 291251
kassa:
  url: https://api.yookassa.ru/v3/payments
  token: test_Ijxh8Z4YH_yCf2S-YsJb7O-VUyQkyFQUEcFcv1FYpBU need new test shop
  shopID: 983924

spring.datasource.url: jdbc:mysql://localhost:3306/cargo_search
spring.datasource.username: root
spring.datasource.password: hWN-h2z-aPE-8dQ
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto: create
#spring.liquibase.enabled: true
#spring.liquibase.change-log: classpath:changelog/db.changelog-master.yaml
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false

server:
  port: 8080
  maxHttpHeaderSize: 20480